from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from app import db

from models import Grade


class User(UserMixin, db.Model):
    """User model backed by SQLAlchemy database.

    Compatible with flask-login and maps to the users table in PostgreSQL.
    """
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    otp = db.Column(db.String(255))
    account_verified = db.Column(db.Boolean, nullable=False, default=False)
    grade = db.Column(db.Integer)

    def set_password(self, password: str) -> None:
        # The string generated by this function automatically includes the method, the hashed pwd+salt, and the salt itself
        self.password = generate_password_hash(password, method="scrypt", salt_length=16)

    def check_password(self, password: str) -> bool:
        """Verify the provided password against the stored hash and salt."""
        if not self.password:
            return False
        return check_password_hash(self.password, password)

    def is_active(self) -> bool:
        """User is active if account is verified (used by flask-login)."""
        return bool(self.account_verified)

    def get_id(self) -> str:
        """Return user ID as string (required by flask-login)."""
        return str(self.id)


def get_user(user_id: int) -> User | None:
	"""Retrieve a user by ID from the database."""
	return User.query.get(user_id)


def find_by_email(email: str) -> User | None:
	"""Find a user by email address."""
	return User.query.filter_by(email=email).first()


def create_user(email: str, password: str, grade: str) -> User:
	"""Create a new user with email and password."""
	user = User(email=email, account_verified=False, grade=grade)
	user.set_password(password)
	db.session.add(user)
	db.session.commit()
	return user

